name: weeath_app_demo
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bloc: ^7.0.0
  build_runner: ^2.0.5
  cached_network_image: ^3.0.0
  dartz: ^0.10.0-nullsafety.2
  dio: ^4.0.0
  equatable: ^2.0.3
  intl: ^0.17.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.1
  pretty_dio_logger: ^1.2.0-beta-1
  rxdart: ^0.27.1
  shared_preferences: ^2.0.6
  geolocator: ^7.2.0+1
  get_it: ^6.1.1
  mocktail: ^0.1.4

dev_dependencies:
  freezed: ^0.14.2
  flutter_test:
    sdk: flutter
  test:
  bloc_test: ^8.0.2
  json_serializable: ^4.1.3
  environment_config: ^3.0.0
  golden_toolkit: ^0.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/

  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir-Roman.ttf
        - asset: assets/fonts/Avenir-Light.ttf
          weight: 300
        - asset: assets/fonts/Avenir-Book.ttf
          weight: 400
        - asset: assets/fonts/Avenir-Medium.ttf
          weight: 500
        - asset: assets/fonts/Avenir-Heavy.ttf
          weight: 800
        - asset: assets/fonts/Avenir-Black.ttf
          weight: 900